- fix obsoletes and conflicts for VirtualBox-gui
    poldek:/all-avail> install VirtualBox52-gui-5.2.26-1.x86_64
    [...]
    error: VirtualBox = 5.2.22-1 is required by installed VirtualBox-gui-5.2.22-1.x86_64
      greedy upgrade VirtualBox-additions-5.2.22-1.noarch to VirtualBox52-additions-5.2.26-1.noarch (unresolved VirtualBox = 5.2.22)
       VirtualBox-additions-5.2.22-1.noarch obsoleted by VirtualBox52-additions-5.2.26-1.noarch